services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notificacao

    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
